# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{adaptive_pay}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Frederik Fix"]
  s.date = %q{2009-11-15}
  s.description = %q{Wrapper around the Paypal Adaptive Payments API}
  s.email = %q{ich@derfred.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "config/adaptive_pay.yml",
     "init.rb",
     "install.rb",
     "lib/adaptive_pay.rb",
     "lib/adaptive_pay/abstract_payment_request.rb",
     "lib/adaptive_pay/callback.rb",
     "lib/adaptive_pay/cancel_preapproval_request.rb",
     "lib/adaptive_pay/interface.rb",
     "lib/adaptive_pay/payment_request.rb",
     "lib/adaptive_pay/preapproval_request.rb",
     "lib/adaptive_pay/recipient.rb",
     "lib/adaptive_pay/refund_request.rb",
     "lib/adaptive_pay/request.rb",
     "lib/adaptive_pay/response.rb",
     "lib/adaptive_pay/sender.rb",
     "spec/adaptive_pay/abstract_payment_request_spec.rb",
     "spec/adaptive_pay/callback_spec.rb",
     "spec/adaptive_pay/cancel_preapproval_request_spec.rb",
     "spec/adaptive_pay/interface_spec.rb",
     "spec/adaptive_pay/payment_request_spec.rb",
     "spec/adaptive_pay/preapproval_request_spec.rb",
     "spec/adaptive_pay/recipient_spec.rb",
     "spec/adaptive_pay/refund_request_spec.rb",
     "spec/adaptive_pay/request_spec.rb",
     "spec/adaptive_pay/response_spec.rb",
     "spec/adaptive_pay/sender_spec.rb",
     "spec/fixtures/config/adaptive_pay.yml",
     "spec/rails_mocks.rb",
     "spec/spec_helper.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/derfred/adaptive_pay}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Wrapper around the Paypal Adaptive Payments API}
  s.test_files = [
    "spec/adaptive_pay/abstract_payment_request_spec.rb",
     "spec/adaptive_pay/callback_spec.rb",
     "spec/adaptive_pay/cancel_preapproval_request_spec.rb",
     "spec/adaptive_pay/interface_spec.rb",
     "spec/adaptive_pay/payment_request_spec.rb",
     "spec/adaptive_pay/preapproval_request_spec.rb",
     "spec/adaptive_pay/recipient_spec.rb",
     "spec/adaptive_pay/refund_request_spec.rb",
     "spec/adaptive_pay/request_spec.rb",
     "spec/adaptive_pay/response_spec.rb",
     "spec/adaptive_pay/sender_spec.rb",
     "spec/rails_mocks.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

